# Generated by Django 3.2.12 on 2022-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_scene_scene_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinschedule',
            name='timing1',
            field=models.CharField(default='00:00', max_length=200),
        ),
    ]
