# Generated by Django 4.0.5 on 2022-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20221106_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene_devices',
            name='time',
        ),
        migrations.AddField(
            model_name='scene_devices',
            name='date',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='scene_devices',
            name='timing',
            field=models.CharField(default='00:00', max_length=200),
        ),
    ]
