# Generated by Django 3.2.12 on 2022-11-22 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20221122_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene_devices',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 22), null=True),
        ),
    ]
