# Generated by Django 3.2.12 on 2022-11-22 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_scene_devices_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene_devices',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 22), null=True),
        ),
    ]
