# Generated by Django 3.2.12 on 2022-11-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20221122_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinschedule',
            name='date',
            field=models.DateField(default='date.today()', null=True),
        ),
    ]
