# Generated by Django 3.2.12 on 2022-11-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_pinschedule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene_devices',
            old_name='status1',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status10',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status3',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status4',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status5',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status6',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status7',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status8',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='status9',
        ),
    ]
