# Generated by Django 3.2.12 on 2022-11-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20221122_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene_devices',
            old_name='scene_device_type1',
            new_name='scene_device_type',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type10',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type2',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type3',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type4',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type5',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type6',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type7',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type8',
        ),
        migrations.RemoveField(
            model_name='scene_devices',
            name='scene_device_type9',
        ),
        migrations.AlterField(
            model_name='pinschedule',
            name='date',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='scene_devices',
            name='date',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='date',
            field=models.DateField(default='2000-01-01', null=True),
        ),
    ]
